[build-system]
requires = ["flit_core >=3.11,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "sky-compass"
version = "0.0.0"
authors = [
    {name = "Chesyon"},
]
description = "CLI utility to convert RAM addresses between releases of PMD:EoS"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["rom-hacking", "game-modding"]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "pmdsky-debug-py >= 10.0.0",
    "pydantic >= 2.13.0"
]

[project.scripts]
sky-compass = "sky_compass.cli:main"

[project.urls]
Repository = "https://github.com/Chesyon/sky-compass"
Issues = "https://github.com/Chesyon/sky-compass/issues"

[tool.ruff]
line-length = 120
